### ISSUE TITLE
Add new players to Default group

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyPermissions#1]
This is more and an enchancement than a bug. Would it be possible to add a feature, that when a new player joins the server (or one that MyPermissions hasn't seen before) it automatically adds them into a default group? I can't find a config setting anywhere for this. 
At the moment I'll have to add people in one by one. 

I'm using ServerTools-Permissions but then MyPermissions for MyTown2. Could I get rid of ServerTools-Permissions and use MyPerms to control ServerTools Commands?

Using: MyPermissions-1.7.10-17-dev

**Comment by dariusc93** [comment]
Currently, from my knowledge, mypermissions doesnt give you a full permission system like servertools does, since servertools hooks into minecraft with a little ASM to inject and modify methods to perform permissions check. This could be done with mypermissions too, but may take a little bit of time.

**Comment by groveham** [comment]
That's fine. Just wondered if it was ever in the works, seems like a good idea if you have your own permissions system to allow it to act as a all-in-one perm system. 

I'm guessing there is no option at the moment to add players to a default group automatically?

**Comment by dariusc93** [comment]
I wouldnt know for sure, but @AfterWind or @legobear154 could probably chime in and give some insight to this question.

**Comment by MuresanSergiu** [comment]
Players are already automatically assigned to the default group when their permissions are checked. I can probably have the same mechanic but on logging in, should be easy to implement.
Thanks for the suggestions, and keep em coming.

**Comment by groveham** [comment]
Yeah on login would be perfect, when players joined they were not automatically assigned any to any permissions groups. Possibly an option to specify which group they are automatically added to in the config would be good for other people too.

**Comment by MuresanSergiu** [comment]
Assigning default group on login has been implemented. As well as some command checking. The only issue with that is, if the command is already not allowed to be executed by the player the perms will not change that. Example: if I add `cmd.stop` to a player, if that player is not OP, he will NOT be able to execute the command `/stop`. That's the current limitation, I hope you can work around that somehow.
