### ISSUE TITLE
Bukkit support not working

### ISSUE THREAD

**Issue by LemADEC** [MyEssentials/MyPermissions#10]
When enabling bukkit support, the parent permission node seems to overtake the target node.
In other words, with MyTown2, a player needs town.cmd to use any command and the same permission node will open all access (a resident can claim and withdraw).
If I change the system to $MyPermissions, then it behave normally.

**Comment by krwminer** [comment]
Are you using PEX for Bukkit?

**Comment by LemADEC** [comment]
Yes, I'm using PermissionsEx for a few years now.
