### ISSUE TITLE
https://ci.mineguild.net/ requires username/password can't get build

### ISSUE THREAD

**Issue by b0bst3r** [MyEssentials/MyPermissions#14]
As per topic, is it possible to fix your site or drop the mypermissions jar on dropbox or something?

Cheers

**Comment by MuresanSergiu** [comment]
I hope this is the latest version that works with your setup.

https://mega.nz/#!P4BWGDZS!5sek8XLH2exA87CBfiCDuDXFmnl9K8oxBvC72YpZ91E

**Comment by nylser** [comment]
Jenkins should be up again, without requiring authentication
