### ISSUE TITLE
MyPerm blocking Servertools commands

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyPermissions#6]
HI,
Just got the updated version of the mod on my test and doing some testing now. I've set it up so that the permissions system is: 
permissionSystem=$MyPermissions
and
fullAccessForOPS=true

But only ops can do commands such as /home and /tpdim even though the ServerTools permissions are set correctly and were working before the update.
Another thing to suggest a bug is, if I remove full access for ops and change it to false then no one can do the commands, suggesting that the MyPermissions mod is blocking the access.

Can you suggest anything to try or test?

**Comment by MuresanSergiu** [comment]
Add the node cmd.(command_name) to all the players.

**Comment by groveham** [comment]
Confirmed this seems to be working for the latest version but I can't get the Mytown2 commands to work. I want players to be able to access pretty much all commands for their towns and their creation, so I've added the node:
mytown.cmd.town
But when ever I test this we just get "You do not have permission to use this command". Am I using the right node to grant permission of the /town command?

**Comment by MuresanSergiu** [comment]
The perm for `/t` is `mytown.cmd`. If that does not work try to add the `cmd.mytown` perm as well. I will look into forever fixing this issue by redesigning how some logic works in the mod.

**Comment by groveham** [comment]
Thank you :) I've got the permissions working for mods and admins but for what ever reason they do not work for normal Players. I'm still looking into it but so far they've all get the right permissions added.

**Comment by groveham** [comment]
Fixed the issue, wasn't with MyTown2, was a ServerTools issue, thanks for your continued work on this mod, it's awesome :D
