### ISSUE TITLE
Withdrawing items without having one in your inventory withdraws but only recieves 1

### ISSUE THREAD

**Issue by rjdunlap** [MyEssentials/MyPermissions#7]
Case 1 (correct):
Inventory 2 Dead Bushes
Bank Inventory 20 Dead Bushes
/town bank withdraw 5
Inventory 7 Dead Bushes
Bank Inventory 15 Dead Bushes

Case 2 (bug):
Inventory 0 Dead Bushes
Bank Inventory 20 Dead Bushes
/town bank withdraw 5
Inventory 1 Dead Bushes
Bank Inventory 15 Dead Bushes

Case 3 (bug):
Inventory 10 Dead Bushes
Bank Inventory 200 Dead Bushes
/town bank withdraw 100
Inventory 64 Dead Bushes
Bank Inventory 100 Dead Bushes

**Comment by MuresanSergiu** [comment]
Why is this in MyPermissions? o.O
What versions are you using?

**Comment by krwminer** [comment]
This was the info he gave me last night:

right now on our server we get a bug with withdrawing our currency item, dead bushes
if you have a dead bush already in your inventory, the withdraw works for the most part fine
but if you don't have one in your inventory, regardless of the withdraw amount (which it takes), you only receive 1
there is also a problem if you go over 1 stack
in the same way for withdrawing

MyTown2 0.2.0b
MyPermissions 1.7.10 - 28 dev
Core 1.13r

**Comment by rjdunlap** [comment]
Yeah, sorry this bug should be against MyTown 2.

Sent from my Windows Phone
