### ISSUE TITLE
[ERROR]: Failed to get player with the UUID:

### ISSUE THREAD

**Issue by sahaka** [MyEssentials/MyPermissions#8]
Our console is currently being spammed with this error message between 15 to 30 times per second:

"[ERROR]: Failed to get player with the UUID: "

It has the same player's UUID every single time and it happens whether he is connected or not. I have tried deleting his player data but that didn't help at all. MyTown works perfectly fine for him but it is crippling our console and adding MBs to our log file.

**Comment by sahaka** [comment]
There are now 2 more UUIDs that if displays. 

[13:32:28 ERROR]: Failed to get player with the UUID: e92e8d45-acb3-4d05-8fb4-0d5e2e5b50d4
[13:32:28 ERROR]: Failed to get player with the UUID: b4b54350-0d08-4c20-9675-5ed0472fe74a

it alternates between these two when the player is logged out.

**Comment by MuresanSergiu** [comment]
So sorry about not replying in such a long time. I'll get it fixed in the next build.

**Comment by krwminer** [comment]
This should be fixed in the latest dev builds of MT2/MEC/MyPermissions.
